version: '3.8'  # Specify the Docker Compose version

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
      - 9300:9300

#   ollama:
#     image: ollama/ollama
#     container_name: ollama
#     volumes:
#       - ollama:/root/.ollama
#     ports:
#       - 11434:11434

#   ollama-command:  # New service for running your command
#     image: ollama/ollama  # Use the same image to have 'ollama' command available
#     depends_on:
#       [ollama]  # Only start after ollama is healthy
#     entrypoint: /bin/bash  # Start a bash shell
#     command: -c "ollama pull phi3"

# volumes:
#   ollama:  # Create a named volume for Ollama data
